
import glob
import os
from scripts.build_support import *

Import ('*')

files = glob.glob (env['rootdir'] + 'src/lib/*.c')
file_list = strip_path_from_files (files)

moslibs = env.Library ('moslibs', file_list)
env.Default(moslibs)
