
import glob
import os
import string

from scripts.build_support import *

Import ('*')

# List of application files and sources defined here
# Example definition:
#
#   app_names_list = ['foo.elf', 'bar.elf']
#   foo_sources = ['foo.c']
#   bar_sources = ['bar1.c', 'bar2.c', 'bar3.c']
#   app_sources_list = [foo_sources, bar_sources]

if env['plat'] == 'linux':
    print "hi"
else:
    app_names_list = ['uart_test_raw.elf']
    uart_test_sources = ['uart_test_raw.c']
    app_sources_list = [uart_test_sources]


# app build methods
loadstat = ARGUMENTS.get('load', '0')
build_app_function(env, app_names_list, app_sources_list, loadstat)
