
import glob
import os
import string
from scripts.build_support import *

Import ('*')


# List of application files and sources defined here
# Example definition:
#
#   app_names_list = ['foo.elf', 'bar.elf']
#   foo_sources = ['foo.c']
#   bar_sources = ['bar1.c', 'bar2.c', 'bar3.c']
#   app_sources_list = [foo_sources, bar_sources]

app_names_list = ['generator.elf','receiver.elf','radio_to_uart.elf', 'gen_and_recv.elf']
generator_sources = ['generator.c', 'generator_app.c']
receiver_sources = ['receiver.c', 'receiver_app.c']
radio_to_uart_sources = ['radio_to_uart.c']
gen_and_recv_sources = ['gen_and_recv.c', 'receiver.c', 'generator.c']
app_sources_list = [generator_sources, receiver_sources, radio_to_uart_sources, gen_and_recv_sources]






# app build methods
loadstat = ARGUMENTS.get('load', '0')
build_app_function(env, app_names_list, app_sources_list, loadstat)
