static char *nag_to_client_dtd = 
""
""
"<!ELEMENT ok EMPTY>"
""
""
"<!ELEMENT error EMPTY>"
"<!ATTLIST error"
"    message CDATA #REQUIRED"
">"
""
""
"<!ELEMENT habs (hab*)>"
""
"<!ELEMENT hab EMPTY>"
"<!ATTLIST hab"
"    type CDATA #REQUIRED"
"    id CDATA #REQUIRED"
">"
""
""
"<!ELEMENT lost-hab EMPTY>"
"<!ATTLIST lost-hab"
"    type CDATA #REQUIRED"
"    id CDATA #REQUIRED"
">"
""
""
"<!ELEMENT nodes (node*)>"
""
""
"<!ELEMENT node (resource+)>"
"<!ATTLIST node"
"    hab-type CDATA #REQUIRED"
"    hab-id CDATA #REQUIRED"
"    node-id CDATA #REQUIRED"
">"
""
""
"<!ELEMENT resource EMPTY>"
"<!ATTLIST resource"
"    hab-type CDATA #IMPLIED"
"    hab-id   CDATA #IMPLIED"
"    node-id  CDATA #IMPLIED"
"    id       CDATA #REQUIRED"
"    flavor   (Sensor|Actuator|Parameter) #REQUIRED"
"    type     CDATA #REQUIRED"
"    value    CDATA #REQUIRED"
"    time     CDATA #REQUIRED"
">"
""
""
"<!ELEMENT lost-node EMPTY>"
"<!ATTLIST lost-node"
"    hab-type CDATA #REQUIRED"
"    hab-id CDATA #REQUIRED"
"    node-id CDATA #REQUIRED"
">"
""
""
;
