#!/bin/bash

#which programming board to use:
#programmer="dapa"
programmer="-dprog=mib510"

#which device to communicate over:
#device="-dlpt=/dev/parport0"
device="-dserial=/dev/ttyS0"

#which processor we're communicating with
dpart="-dpart=ATmega128"

echo "Using $programmer programming board"

#write the fuse so it allows serial programming
echo "disabling on chip debugging system"

uisp $programmer $device $dpart --wr_fuse_h=0xd0

echo "done."
