#!/bin/bash

rm -f boot.elf boot.srec

cp ../build/mica2/src/mos/kernel/avr/boot/boot.elf .

if [ ! -f ./boot.srec ]
then
      avr-objcopy --target=srec boot.elf boot.srec
fi

#which programming board to use:
programmer="-dprog=dapa"

#which device to communicate over:
device="-dlpt=/dev/parport0"

echo "Using $programmer programming board"

#write the fuse so it allows serial programming
uisp $programmer $device $dpart --wr_fuse_h=0x10
#erase what's there
uisp $programmer $device $dpart --erase
#send our boot-loader
uisp $programmer $device $dpart --upload if=boot.srec
#verify the file
uisp $programmer $device $dpart --verify if=boot.srec

echo "done."
