
import glob
import os
import string
from scripts.build_support import *

Import ('*')


# List of application files and sources defined here
# Example definition:
#
#   app_names_list = ['foo.elf', 'bar.elf']
#   foo_sources = ['foo.c']
#   bar_sources = ['bar1.c', 'bar2.c', 'bar3.c']
#   app_sources_list = [foo_sources, bar_sources]

app_names_list = ['thread.elf','nothread.elf','dev.elf','nodev.elf','com.elf','nocom.elf','thread-spam.elf']
thread_sources = ['kernel-thread.c']
nothread_sources = ['kernel-nothread.c']
dev_sources = ['dev.c']
nodev_sources = ['nodev.c']
com_sources = ['com.c']
nocom_sources = ['nocom.c']
thread_spam_sources = ['thread-spam.c']
app_sources_list = [thread_sources, nothread_sources, dev_sources, nodev_sources, com_sources, nocom_sources, thread_spam_sources]






# app build methods
loadstat = ARGUMENTS.get('load', '0')
build_app_function(env, app_names_list, app_sources_list, loadstat)
